name = "cf-kv-test"
compatibility_date = "2024-01-01"

# Pages configuration
pages_build_output_dir = "dist"

# Environment variables
[vars]
NODE_ENV = "production"
KV_NAMESPACE_ID = "70e8edb9dc214313be1fdd4bf20bb44d"
